"""initial schema

Revision ID: 04d0fd421b67
Revises: 
Create Date: 2026-10-04 09:53:06.932378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d0fd421b67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('outsource_kinds', sa.JSON(), nullable=False),
    sa.Column('contact', sa.String(length=300), nullable=False),
    sa.Column('rating', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('clearance', sa.Integer(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_login'), ['login'], unique=True)

    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('work_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('capacity_hours_per_day', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('route', sa.String(length=16), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_messages_conversation'), ['conversation'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_user_id'), ['user_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)

    op.create_table('change_notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reason_code', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('draft', 'review', 'approved', 'rejected', 'implemented', name='changestatus', native_enum=False, length=32), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('wip_disposition', sa.String(length=16), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('implemented_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('change_notices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_notices_status'), ['status'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('item_type', sa.Enum('assembly', 'part', 'purchased', 'outsourced', 'outsourced_op', 'fastener', 'material', 'tooling', 'product', name='itemtype', native_enum=False, length=32), nullable=False),
    sa.Column('outsource_kind', sa.Enum('machining', 'coating', 'heat_treatment', 'welding', 'casting', 'sheet_metal', 'pcb', 'other', name='outsourcekind', native_enum=False, length=32), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('material', sa.String(length=200), nullable=False),
    sa.Column('mass_kg', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lifecycle', sa.Enum('draft', 'in_review', 'released', 'obsolete', name='lifecycle', native_enum=False, length=32), nullable=False),
    sa.Column('confidentiality', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('lot_size', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('std_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('default_supplier_id', sa.Integer(), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['default_supplier_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_items_item_type'), ['item_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_name'), ['name'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'confirmed', 'partial', 'received', 'closed', 'cancelled', name='postatus', native_enum=False, length=32), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_status'), ['status'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('role_code', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['change_notices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_notice_id'), ['notice_id'], unique=False)

    op.create_table('change_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('target_item_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('add', 'remove', 'set_qty', 'replace', name='changeaction', native_enum=False, length=32), nullable=False),
    sa.Column('child_item_id', sa.Integer(), nullable=True),
    sa.Column('new_child_item_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['child_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['new_child_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['notice_id'], ['change_notices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_lines_notice_id'), ['notice_id'], unique=False)

    op.create_table('item_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('rev', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_review', 'released', 'obsolete', name='lifecycle', native_enum=False, length=32), nullable=False),
    sa.Column('change_notice_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['change_notice_id'], ['change_notices.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'rev')
    )
    with op.batch_alter_table('item_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_revisions_item_id'), ['item_id'], unique=False)

    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('work_center_id', sa.Integer(), nullable=True),
    sa.Column('setup_hours', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('run_hours', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('outsourced', sa.Boolean(), nullable=False),
    sa.Column('outsource_kind', sa.Enum('machining', 'coating', 'heat_treatment', 'welding', 'casting', 'sheet_metal', 'pcb', 'other', name='outsourcekind', native_enum=False, length=32), nullable=True),
    sa.Column('outsource_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tooling_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tooling_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_item_id'), ['item_id'], unique=False)

    op.create_table('plan_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('customer', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_lines_due_date'), ['due_date'], unique=False)

    op.create_table('stock_balances',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reserved', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'warehouse_id')
    )
    op.create_table('bom_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_revision_id', sa.Integer(), nullable=False),
    sa.Column('child_item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['child_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['parent_revision_id'], ['item_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bom_lines', schema=None) as batch_op:
        batch_op.create_index('ix_bom_child', ['child_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bom_lines_parent_revision_id'), ['parent_revision_id'], unique=False)

    op.create_table('kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('serial_numbers', sa.String(length=500), nullable=False),
    sa.Column('plan_line_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['plan_line_id'], ['plan_lines.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['item_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('kit_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.Column('parent_line_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty_per', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('required_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('issued_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_line_id'], ['kit_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kit_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kit_lines_kit_id'), ['kit_id'], unique=False)

    op.create_table('po_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('received_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('kit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('po_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_po_lines_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_po_lines_order_id'), ['order_id'], unique=False)

    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('done_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('kit_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('actual_hours', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_orders_status'), ['status'], unique=False)

    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_line_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('accepted_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('rejected_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('lot', sa.String(length=64), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.Column('defects', sa.Text(), nullable=False),
    sa.Column('certificate', sa.String(length=200), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['po_line_id'], ['po_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspections_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_status'), ['status'], unique=False)

    op.create_table('stock_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('move_type', sa.Enum('receipt', 'issue', 'output', 'transfer', 'writeoff', 'adjustment', 'to_outsource', name='movetype', native_enum=False, length=32), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('from_wh_id', sa.Integer(), nullable=True),
    sa.Column('to_wh_id', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('lot', sa.String(length=64), nullable=False),
    sa.Column('doc_ref', sa.String(length=100), nullable=False),
    sa.Column('kit_id', sa.Integer(), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['from_wh_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.ForeignKeyConstraint(['to_wh_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_moves', schema=None) as batch_op:
        batch_op.create_index('ix_move_item_ts', ['item_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_moves_move_type'), ['move_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_moves_ts'), ['ts'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('debit', sa.String(length=16), nullable=False),
    sa.Column('credit', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('stock_move_id', sa.Integer(), nullable=True),
    sa.Column('memo', sa.String(length=300), nullable=False),
    sa.Column('exported', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['stock_move_id'], ['stock_moves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_ts'), ['ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_ts'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('stock_moves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_moves_ts'))
        batch_op.drop_index(batch_op.f('ix_stock_moves_move_type'))
        batch_op.drop_index('ix_move_item_ts')

    op.drop_table('stock_moves')
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspections_status'))
        batch_op.drop_index(batch_op.f('ix_inspections_item_id'))

    op.drop_table('inspections')
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_status'))

    op.drop_table('work_orders')
    with op.batch_alter_table('po_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_po_lines_order_id'))
        batch_op.drop_index(batch_op.f('ix_po_lines_item_id'))

    op.drop_table('po_lines')
    with op.batch_alter_table('kit_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kit_lines_kit_id'))

    op.drop_table('kit_lines')
    op.drop_table('kits')
    with op.batch_alter_table('bom_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bom_lines_parent_revision_id'))
        batch_op.drop_index('ix_bom_child')

    op.drop_table('bom_lines')
    op.drop_table('stock_balances')
    with op.batch_alter_table('plan_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_lines_due_date'))

    op.drop_table('plan_lines')
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_item_id'))

    op.drop_table('operations')
    with op.batch_alter_table('item_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_revisions_item_id'))

    op.drop_table('item_revisions')
    with op.batch_alter_table('change_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_lines_notice_id'))

    op.drop_table('change_lines')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_notice_id'))

    op.drop_table('approvals')
    op.drop_table('user_roles')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_status'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_name'))
        batch_op.drop_index(batch_op.f('ix_items_item_type'))
        batch_op.drop_index(batch_op.f('ix_items_code'))

    op.drop_table('items')
    with op.batch_alter_table('change_notices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_notices_status'))

    op.drop_table('change_notices')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity'))

    op.drop_table('audit_log')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_messages_conversation'))

    op.drop_table('ai_messages')
    op.drop_table('work_centers')
    op.drop_table('warehouses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_login'))

    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('partners')
    op.drop_table('connectors')
    # ### end Alembic commands ###
