"""assembly steps facts and 3d models

Revision ID: 30c13a32da18
Revises: 04d0fd421b67
Create Date: 2026-10-04 15:45:38.487243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c13a32da18'
down_revision: Union[str, Sequence[str], None] = '04d0fd421b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('source_format', sa.String(length=16), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_models_item_id'), ['item_id'], unique=True)

    with op.batch_alter_table('kit_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skipped', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('done_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('done_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_kit_lines_done_by_id_users', 'users', ['done_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kit_lines', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_kit_lines_done_by_id_users', type_='foreignkey')
        batch_op.drop_column('done_by_id')
        batch_op.drop_column('done_at')
        batch_op.drop_column('skipped')

    with op.batch_alter_table('item_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_models_item_id'))

    op.drop_table('item_models')
    # ### end Alembic commands ###
